name: Build and unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: dotnet restore 
      run: dotnet restore --ignore-failed-sources
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: C# Code Analyzer
      uses: microsoft/CSharpCodeAnalyzer@v0.1-beta
      with:
        # The path where the binaries (.dll and .pdb) are located.
        binary-path: artifacts/bin
        # Whether to opt out telemetry collection.
        opt-out-telemetry: true
        # Repository name.
        repository: vchirikov/limiter
